### DISCUSSION TITLE
使用github action 实现自动/半自动化的编译和部署

### DISCUSSION THREAD

**Discussion by chengjun** [chengjun/mybook#12] [Ideas]
# 《计算传播学基础》讲义

https://chengjun.github.io/mybook/

## 1. 在本地运行mybook中代码

可以修改或新增notebook。

注意：📢 如果新增notebook需要同步添加到 **_toc.yml**

## 2. 使用Github Desktop上传

![image](https://github.com/chengjun/mybook/assets/543384/854df8ec-fb7a-4c12-bf6e-b3dd65c0aae7)

## 3. 在action中手动运行deploy代码

![image](https://github.com/chengjun/mybook/assets/543384/d655fa50-523d-4783-a655-a2f5acda6a9b)

![image](https://user-images.githubusercontent.com/543384/142763618-9a1fecef-7404-4811-a44c-d501f4699e58.png)

pages-build-deployment也会接下来自动运行，待其运行结束后，gh-pages就实现了更新。

**Comment by chengjun** [comment]
I test this idea on this repo: 

https://github.com/chengjun/sample-notebooks/

it works smoothly. 

https://chengjun.github.io/sample-notebooks/SampleNotebook.html

and this is the github action file:

https://github.com/chengjun/sample-notebooks/blob/main/.github/workflows/manual.yml

```
name: Deploy to gh-pages
# https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository
# When you use deploy_key, set your private key to the repository which includes this action
# and set your public key to your external repository.
# https://github.com/wowchemy/wowchemy-hugo-modules/issues/2240

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
  
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # - uses: pre-commit/action@v2.0.0
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book
        
    - name: Build
      run: | 
        jupyter-book build .
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
```

**Comment by chengjun** [comment]
```
The Table of Contents file is malformed: toc is not a mapping: <class 'list'>
You may need to migrate from the old format, using:

	jupyter-book toc migrate /home/runner/work/mybook/mybook/_toc.yml -o /home/runner/work/mybook/mybook/_toc.yml
```

**Reply by chengjun** [reply]
After revising https://github.com/chengjun/mybook/blob/main/_toc.yml, it finally works! 

https://github.com/chengjun/mybook/runs/3413416739?check_suite_focus=true

**Reply by chengjun** [reply]
```
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
```

Change it from push trigger to manually trigger. 

![image](https://user-images.githubusercontent.com/543384/130657948-5cc9b816-5a04-49db-88d4-53e043d42e62.png)
